FROM docker.io/library/maven:3.9.6-eclipse-temurin-21-alpine as build

COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM docker.io/library/jetty:11.0.19-jre21-alpine-eclipse-temurin
USER jetty
COPY --from=build  --chown=jetty:jetty /home/app/target/*.war /var/lib/jetty/webapps/root.war

EXPOSE 8081
CMD java -jar "$JETTY_HOME/start.jar" jetty.http.port=8081
